# CMake generated Testfile for 
# Source directory: /home/fernando/charts/beamform_project
# Build directory: /home/fernando/charts/beamform_project
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[contract]=] "/home/fernando/charts/beamform_project/test_contract")
set_tests_properties([=[contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fernando/charts/beamform_project/CMakeLists.txt;186;add_test;/home/fernando/charts/beamform_project/CMakeLists.txt;0;")
add_test([=[geometry]=] "/home/fernando/charts/beamform_project/test_geometry")
set_tests_properties([=[geometry]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fernando/charts/beamform_project/CMakeLists.txt;191;add_test;/home/fernando/charts/beamform_project/CMakeLists.txt;0;")
add_test([=[synthetic_data]=] "/home/fernando/charts/beamform_project/test_synthetic_data")
set_tests_properties([=[synthetic_data]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fernando/charts/beamform_project/CMakeLists.txt;196;add_test;/home/fernando/charts/beamform_project/CMakeLists.txt;0;")
add_test([=[cpu_beamformer]=] "/home/fernando/charts/beamform_project/test_cpu_beamformer")
set_tests_properties([=[cpu_beamformer]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fernando/charts/beamform_project/CMakeLists.txt;201;add_test;/home/fernando/charts/beamform_project/CMakeLists.txt;0;")
add_test([=[beam_tracker]=] "/home/fernando/charts/beamform_project/test_beam_tracker")
set_tests_properties([=[beam_tracker]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fernando/charts/beamform_project/CMakeLists.txt;206;add_test;/home/fernando/charts/beamform_project/CMakeLists.txt;0;")
add_test([=[cpu_opt_beam_tracker]=] "/home/fernando/charts/beamform_project/test_cpu_opt_beam_tracker")
set_tests_properties([=[cpu_opt_beam_tracker]=] PROPERTIES  LABELS "tracker;optimization;validation" TIMEOUT "120" _BACKTRACE_TRIPLES "/home/fernando/charts/beamform_project/CMakeLists.txt;217;add_test;/home/fernando/charts/beamform_project/CMakeLists.txt;0;")
add_test([=[beam_tracker_opt]=] "/home/fernando/charts/beamform_project/test_beam_tracker_opt")
set_tests_properties([=[beam_tracker_opt]=] PROPERTIES  LABELS "tracker;optimization;validation" TIMEOUT "120" _BACKTRACE_TRIPLES "/home/fernando/charts/beamform_project/CMakeLists.txt;233;add_test;/home/fernando/charts/beamform_project/CMakeLists.txt;0;")
add_test([=[beam_tracker_opt_v2]=] "/home/fernando/charts/beamform_project/test_beam_tracker_opt_v2")
set_tests_properties([=[beam_tracker_opt_v2]=] PROPERTIES  LABELS "tracker;optimization;validation" TIMEOUT "120" _BACKTRACE_TRIPLES "/home/fernando/charts/beamform_project/CMakeLists.txt;250;add_test;/home/fernando/charts/beamform_project/CMakeLists.txt;0;")
add_test([=[temporal_integration]=] "/home/fernando/charts/beamform_project/test_temporal_integration")
set_tests_properties([=[temporal_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fernando/charts/beamform_project/CMakeLists.txt;259;add_test;/home/fernando/charts/beamform_project/CMakeLists.txt;0;")
add_test([=[quantization]=] "/home/fernando/charts/beamform_project/test_quantization")
set_tests_properties([=[quantization]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fernando/charts/beamform_project/CMakeLists.txt;264;add_test;/home/fernando/charts/beamform_project/CMakeLists.txt;0;")
add_test([=[cuda_frame_contract]=] "/home/fernando/charts/beamform_project/test_cuda_frame_contract")
set_tests_properties([=[cuda_frame_contract]=] PROPERTIES  LABELS "contract" _BACKTRACE_TRIPLES "/home/fernando/charts/beamform_project/CMakeLists.txt;269;add_test;/home/fernando/charts/beamform_project/CMakeLists.txt;0;")
add_test([=[cuda_point_source]=] "/home/fernando/charts/beamform_project/test_cuda_point_source")
set_tests_properties([=[cuda_point_source]=] PROPERTIES  LABELS "cuda;physics" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/fernando/charts/beamform_project/CMakeLists.txt;276;add_test;/home/fernando/charts/beamform_project/CMakeLists.txt;0;")
add_test([=[cuda_packed]=] "/home/fernando/charts/beamform_project/test_cuda_packed")
set_tests_properties([=[cuda_packed]=] PROPERTIES  LABELS "cuda;packed;validation" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/fernando/charts/beamform_project/CMakeLists.txt;285;add_test;/home/fernando/charts/beamform_project/CMakeLists.txt;0;")
add_test([=[cuda_temporal_integration]=] "/home/fernando/charts/beamform_project/test_cuda_temporal_integration")
set_tests_properties([=[cuda_temporal_integration]=] PROPERTIES  LABELS "cuda;temporal-integration;validation" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/fernando/charts/beamform_project/CMakeLists.txt;295;add_test;/home/fernando/charts/beamform_project/CMakeLists.txt;0;")
add_test([=[cuda_quantization]=] "/home/fernando/charts/beamform_project/test_cuda_quantization")
set_tests_properties([=[cuda_quantization]=] PROPERTIES  LABELS "cuda;quantization;validation" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/fernando/charts/beamform_project/CMakeLists.txt;304;add_test;/home/fernando/charts/beamform_project/CMakeLists.txt;0;")
add_test([=[cuda_frame_pipeline]=] "/home/fernando/charts/beamform_project/test_cuda_frame_pipeline")
set_tests_properties([=[cuda_frame_pipeline]=] PROPERTIES  LABELS "cuda;contract;validation" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/fernando/charts/beamform_project/CMakeLists.txt;316;add_test;/home/fernando/charts/beamform_project/CMakeLists.txt;0;")
add_test([=[cuda_offline_runner]=] "/home/fernando/charts/beamform_project/test_cuda_offline_runner")
set_tests_properties([=[cuda_offline_runner]=] PROPERTIES  LABELS "cuda;contract;validation" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/fernando/charts/beamform_project/CMakeLists.txt;326;add_test;/home/fernando/charts/beamform_project/CMakeLists.txt;0;")
add_test([=[cuda_tracker_v2]=] "/home/fernando/charts/beamform_project/test_cuda_tracker_v2")
set_tests_properties([=[cuda_tracker_v2]=] PROPERTIES  LABELS "cuda;tracker;validation" TIMEOUT "120" _BACKTRACE_TRIPLES "/home/fernando/charts/beamform_project/CMakeLists.txt;335;add_test;/home/fernando/charts/beamform_project/CMakeLists.txt;0;")
add_test([=[benchmark_config]=] "/home/fernando/charts/beamform_project/benchmark_cpu_cuda" "--dry-run" "--n-ant" "32,64" "--beams" "16,32,64,128" "--times" "15360,24576,30720" "--validation-time" "16")
set_tests_properties([=[benchmark_config]=] PROPERTIES  LABELS "cuda;benchmark" TIMEOUT "10" _BACKTRACE_TRIPLES "/home/fernando/charts/beamform_project/CMakeLists.txt;341;add_test;/home/fernando/charts/beamform_project/CMakeLists.txt;0;")
